import { Router } from "express";

import academicFieldRoutes from "./academicFieldRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import authRoutes from "./authRoutes.js";
import careerGoalRoutes from "./careerGoalRoutes.js";
import careerRoutes from "./careerRoutes.js";
import chatRoutes from "./chatRoutes.js";
import challengeRoutes from "./challengeRoutes.js";
import companyRoutes from "./companyRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import profileRoutes from "./profileRoutes.js";
import quizAttemptRoutes from "./quizAttemptRoutes.js";
import quizRoutes from "./quizRoutes.js";
import recommendationRoutes from "./recommendationRoutes.js";
import reportRoutes from "./reportRoutes.js";
import resourceRoutes from "./resourceRoutes.js";
import roadmapRoutes from "./roadmapRoutes.js";
import roadmapTaskRoutes from "./roadmapTaskRoutes.js";
import jobRoutes from "./jobRoutes.js";
import savedJobRoutes from "./savedJobRoutes.js";
import skillCategoryRoutes from "./skillCategoryRoutes.js";
import skillGapRoutes from "./skillGapRoutes.js";
import skillRoutes from "./skillRoutes.js";
import systemRoutes from "./systemRoutes.js";
import taskResourceRoutes from "./taskResourceRoutes.js";
import userRoutes from "./userRoutes.js";
import userSkillRoutes from "./userSkillRoutes.js";
import uploadRoutes from "./uploadRoutes.js";

const v1Routes = Router();

v1Routes.use("/system", systemRoutes);
v1Routes.use("/auth", authRoutes);
v1Routes.use("/analytics", analyticsRoutes);
v1Routes.use("/users", userRoutes);
v1Routes.use("/profiles", profileRoutes);
v1Routes.use("/academic-fields", academicFieldRoutes);
v1Routes.use("/skill-categories", skillCategoryRoutes);
v1Routes.use("/skills", skillRoutes);
v1Routes.use("/careers", careerRoutes);
v1Routes.use("/career-goals", careerGoalRoutes);
v1Routes.use("/user-skills", userSkillRoutes);
v1Routes.use("/skill-gap", skillGapRoutes);
v1Routes.use("/roadmaps", roadmapRoutes);
v1Routes.use("/roadmap-tasks", roadmapTaskRoutes);
v1Routes.use("/resources", resourceRoutes);
v1Routes.use("/task-resources", taskResourceRoutes);
v1Routes.use("/quizzes", quizRoutes);
v1Routes.use("/quiz-attempts", quizAttemptRoutes);
v1Routes.use("/chat", chatRoutes);
v1Routes.use("/recommendations", recommendationRoutes);
v1Routes.use("/jobs", jobRoutes);
v1Routes.use("/companies", companyRoutes);
v1Routes.use("/saved-jobs", savedJobRoutes);
v1Routes.use("/challenges", challengeRoutes);
v1Routes.use("/notifications", notificationRoutes);
v1Routes.use("/reports", reportRoutes);
v1Routes.use("/uploads", uploadRoutes);

export default v1Routes;
